### ISSUE TITLE
Code Improvement

### ISSUE THREAD

**Issue by Muhammad-Saad12** [grayhatdevelopers/vite-react-ts-multiplayer-game#1]
Code quality can be improved for better understanding. Some of the recommendations are as follows

- [x] Making styles={{ property : "attribute" }} to styles={{styles}} 
- [x] writing the method within onclick to defining it in component top level , onclick{()=>const a=somthing; xyz logic} to onClick={doSomething}
- [x] React.useEffect to useEffect

**Comment by SaadBazaz** [comment]
Thanks for the report, @Muhammad-Saad12 . Yes, this needs some code quality standardization. Will look into it.

**Comment by SaadBazaz** [comment]
Resolved. Appreciate it. Please do keep an eye out for the latest version ❤️
